# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Numerical Modeling Lecture Notes
author: Joao Bettencourt
#logo: UiBlogo_Eng_gray_left.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - numerical-modeling.bib
bibtex_reference_style: 
  - author_year

# Information about where the book exists on the web
repository:
  url: https://github.com/joaobuibergen/numerical-modeling-notes  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - colon_fence

sphinx:
  config:
    nb_execution_show_tb: True
    
launch_buttons:
  thebe                  : true
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
