name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - main  # Or your primary branch

permissions:
  contents: read
  pages: write # Required for deploying to GitHub Pages
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python environment and install dependencies
        run: |
          uv python install  # Installs Python if not present, respecting pyproject.toml
          uv sync            # Installs dependencies from pyproject.toml or uv.lock

      - name: Build Jupyter Book
        run: uv run jupyter-book build GEOF211_book 

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_path: 'GEOF211_book/_build/html' 